export const testData = [
  {
    bountyId: 0,
    bountyName: 'Cover Index Construction and Updates with Unit Test',
    createdBy: 'ARK Builders',
    difficulty: 'Hard',
    language: 'SQL',
    rewardAmountDollar: '$103.04',
    rewardAmountCrypto: '109.28 ADA',
    createdAt: new Date(),
    favorites: 0,
  },
  {
    bountyId: 1,
    bountyName: 'Integration of Vite with Trust Wallet',
    createdBy: 'Vite LAbs',
    difficulty: 'Medium',
    language: 'Solidity',
    rewardAmountDollar: '$4497.75',
    rewardAmountCrypto: '4770.31 ADA',
    createdAt: new Date(),
    favorites: 0,
  },
  {
    bountyId: 2,
    bountyName: 'FVM Milestone 1 Bug Bounty Program',
    createdBy: 'Filecoin',
    difficulty: 'Hard',
    language: 'JavaScript',
    rewardAmountDollar: '$4910.00',
    rewardAmountCrypto: '5207.55 ADA',
    createdAt: new Date(),
    favorites: 0,
  },
  {
    bountyId: 3,
    bountyName: 'Integration Guide: Lit Protocol',
    createdBy: 'Tableland Network',
    difficulty: 'Easy',
    language: 'CSS',
    rewardAmountDollar: '$310.40',
    rewardAmountCrypto: '329.21 ADA',
    createdAt: new Date(),
    favorites: 0,
  },
];
